### ISSUE TITLE
ModuleNotFoundError: No module named 'SofaViscoElastic'

### ISSUE THREAD

**Issue by Dong-Le-gnoD** [SofaDefrost/SofaViscoElastic#20]
Hi,

I have a problem with run the example of the plugin.
![Screenshot from 2024-04-19 17-26-58](https://github.com/SofaDefrost/SofaViscoElastic/assets/117520761/f4fa8b10-429b-4a43-bc2f-972b3e0ccce6)

Even though SofaViscoElastic is in the Plugin Manager and I added to the plugin_list.conf.default file, the problem is still the same.
![Screenshot from 2024-04-19 17-27-25](https://github.com/SofaDefrost/SofaViscoElastic/assets/117520761/8e4f095a-70f5-4f9c-af2e-3c4f01cc9df6)

Thank you!

**Comment by pasqualeferr94** [comment]
Hello @Dong-Le-gnoD which OS are you using?

**Comment by Dong-Le-gnoD** [comment]
Hi, I am using Ubuntu 20.04

**Comment by pasqualeferr94** [comment]
Do you put It on the folder src/applications/plugins?

**Comment by Dong-Le-gnoD** [comment]
I followed the in-tree build from SOFA website https://www.sofa-framework.org/community/doc/plugins/build-a-plugin-from-sources/
Should I move all plugins to src/application/plugins? Does this also mean that I follow the same as the tutorial but changing the repository?

**Comment by pasqualeferr94** [comment]
usually yes.
In the src/application/plugins, there is a CMakeList.txt. Open the file, add the plugin to the list, then configure with cmake-gui and compile.

Anyway, we are working to make it compatible with binaries and available for the other OS (MacOS and Windows). It will be a matter of day. I will keep you updated.

**Comment by pasqualeferr94** [comment]
Hello @Dong-Le-gnoD ,
the  plugin is now compatible with other OS; you can check it. I close the issue.
